# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 22:51
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('winner', models.IntegerField()),
                ('loser', models.IntegerField()),
                ('excluded', models.BooleanField()),
                ('result', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('ratings', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('regions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mu', models.FloatField(default=25.0)),
                ('sigma', models.FloatField(default=8.333333333333334)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('type', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('region', models.TextField()),
                ('url', models.TextField()),
                ('matches', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('players', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
            ],
        ),
    ]
