# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.TextField(),
        ),
    ]
