# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerr', '0002_auto_20170614_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='loser',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.TextField(),
        ),
    ]
